//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackTranslationHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackTranslationHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///        &lt;script type=&quot;text/javascript&quot;&gt;
        ///{0}
        ///        &lt;/script&gt;
        ///{1}
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///{2}
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string BackTranslationHelperHtmlPage {
            get {
                return ResourceManager.GetString("BackTranslationHelperHtmlPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BackTranslationHelperJavaScriptFunctions {
            get {
                return ResourceManager.GetString("BackTranslationHelperJavaScriptFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillDownHS {
            get {
                object obj = ResourceManager.GetObject("FillDownHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button id=&quot;{0}&quot; name=&quot;{1}&quot; onMouseUp=&quot;{2}&quot; title=&quot;{3}&quot;&gt;&lt;img src=&quot;{4}&quot;&gt;&lt;/button&gt;.
        /// </summary>
        internal static string HTML_ButtonImageToolTip {
            get {
                return ResourceManager.GetString("HTML_ButtonImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .{0} {{
        ///      font-family: &quot;{1}&quot;;
        ///      font-size: {2} pt;
        ///      color: {3};
        ///      direction: {4};
        ///      text-align: {5};
        ///  }}.
        /// </summary>
        internal static string HTML_LangStyle {
            get {
                return ResourceManager.GetString("HTML_LangStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;{0}&quot;&gt;{1}&lt;/p&gt;.
        /// </summary>
        internal static string HTML_ParagraphText {
            get {
                return ResourceManager.GetString("HTML_ParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///  body    {{ margin:0 }}
        ///  textarea {{ 
        ///      width:100%; 
        ///      overflow:visible;
        ///  }}
        ///  table {{
        ///   font-size: {0};
        ///  }}
        ///  button 
        ///  {{
        ///    font-size: {0};
        ///    padding: 0 2px;
        ///    overflow: visible;
        ///  }}  
        ///  p 
        ///  {{
        ///    margin-top: 0em; 
        ///    margin-bottom: 0em;
        ///  }} 
        ///  {1}
        ///  .hasPlaceholder {{
        ///     color: #777;
        ///  }}
        ///  .readonly {{
        ///    background-color:Azure;
        ///  }}
        ///  .highlight {{
        ///	background-color:#0099ff;
        ///	color:white;
        ///  }}
        ///&lt;/style&gt;.
        /// </summary>
        internal static string HTML_StyleDefinition {
            get {
                return ResourceManager.GetString("HTML_StyleDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;table style=&quot;width:100%;&quot; border=&quot;1&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///  {0}
        ///  &lt;/table&gt;.
        /// </summary>
        internal static string HTML_Table {
            get {
                return ResourceManager.GetString("HTML_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;{0}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCell {
            get {
                return ResourceManager.GetString("HTML_TableCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td id=&quot;{0}&quot;&gt;{1}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellId {
            get {
                return ResourceManager.GetString("HTML_TableCellId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td width=&quot;{0}%&quot; valign=&quot;top&quot;&gt;{1}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellWidthAlignTop {
            get {
                return ResourceManager.GetString("HTML_TableCellWidthAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;tr&gt;
        ///    {0}
        ///  &lt;/tr&gt;
        ///    .
        /// </summary>
        internal static string HTML_TableRow {
            get {
                return ResourceManager.GetString("HTML_TableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;textarea id=&quot;{0}&quot; class=&quot;{1}&quot;&gt;{2}&lt;/textarea&gt;.
        /// </summary>
        internal static string HTML_Textarea {
            get {
                return ResourceManager.GetString("HTML_Textarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.org/license */
        ///!function(e,t){&quot;use strict&quot;;&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=e.document?t(e,!0):function(e){if(!e.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return t(e)}:t(e)}(&quot;undefined&quot;!=typeof window?window:this,function(C,e){&quot;use strict&quot;;var t=[],r=Object.getPrototypeOf,s=t.slice,g=t.flat?function(e){return t.flat.call(e)}:function(e){return t.concat.apply([],e)},u=t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_3_6_0_min {
            get {
                return ResourceManager.GetString("jquery_3_6_0_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pindown {
            get {
                object obj = ResourceManager.GetObject("pindown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pinup {
            get {
                object obj = ResourceManager.GetObject("pinup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
