//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackTranslationHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideLabels {
            get {
                return ((bool)(this["HideLabels"]));
            }
            set {
                this["HideLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MapProjectNameToEcTranslators {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MapProjectNameToEcTranslators"]));
            }
            set {
                this["MapProjectNameToEcTranslators"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MapProjectNameToSourceFontOverride {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MapProjectNameToSourceFontOverride"]));
            }
            set {
                this["MapProjectNameToSourceFontOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MapProjectNameToTargetFontOverride {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MapProjectNameToTargetFontOverride"]));
            }
            set {
                this["MapProjectNameToTargetFontOverride"] = value;
            }
        }
    }
}
