using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SilEncConverters40
{
    partial class Py3ScriptAutoConfigDialog
    {
        #region Windows Form Designer generated code
        // This code does not get generated by Designer, so modify it directly.
        private void InitializeComponent()
        {
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.labelScriptFile = new System.Windows.Forms.Label();
            this.textBoxFileSpec = new System.Windows.Forms.TextBox();
            this.buttonBrowse = new System.Windows.Forms.Button();
            this.labelPython3Path = new System.Windows.Forms.Label();
            this.textBoxPython3Path = new System.Windows.Forms.TextBox();
            this.buttonPython3Browse = new System.Windows.Forms.Button();
            this.openFileDialogBrowse = new System.Windows.Forms.OpenFileDialog();
            this.tabControl.SuspendLayout();
            this.tabPageSetup.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabPageSetup
            // 
            this.tabPageSetup.Controls.Add(this.tableLayoutPanel1);
            // 
            // buttonApply
            // 
            this.helpProvider.SetHelpString(this.buttonApply, "Click this button to apply the configured values for this converter");
            this.helpProvider.SetShowHelp(this.buttonApply, true);
            // 
            // buttonCancel
            // 
            this.helpProvider.SetHelpString(this.buttonCancel, "Click this button to cancel this dialog");
            this.helpProvider.SetShowHelp(this.buttonCancel, true);
            // 
            // buttonOK
            // 
            this.helpProvider.SetHelpString(this.buttonOK, "Click this button to accept the configured values for this converter");
            this.helpProvider.SetShowHelp(this.buttonOK, true);
            // 
            // buttonSaveInRepository
            // 
            this.helpProvider.SetHelpString(this.buttonSaveInRepository, "Click to add this converter to the system repository permanently.");
            this.helpProvider.SetShowHelp(this.buttonSaveInRepository, true);
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 3;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 104F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel1.Controls.Add(this.labelScriptFile, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.textBoxFileSpec, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.buttonBrowse, 2, 0);
            this.tableLayoutPanel1.Controls.Add(this.labelPython3Path, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.textBoxPython3Path, 1, 1);
            this.tableLayoutPanel1.Controls.Add(this.buttonPython3Browse, 2, 1);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 2;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(596, 394);
            this.tableLayoutPanel1.TabIndex = 1;
            // 
            // labelScriptFile
            // 
            this.labelScriptFile.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.labelScriptFile.AutoSize = true;
            this.labelScriptFile.Location = new System.Drawing.Point(14, 18);
            this.labelScriptFile.Name = "labelScriptFile";
            this.labelScriptFile.Size = new System.Drawing.Size(87, 13);
            this.labelScriptFile.TabIndex = 0;
            this.labelScriptFile.Text = "Python script file:";
            // 
            // textBoxFileSpec
            // 
            this.textBoxFileSpec.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.textBoxFileSpec.Location = new System.Drawing.Point(104, 15);
            this.textBoxFileSpec.Margin = new System.Windows.Forms.Padding(0);
            this.textBoxFileSpec.Name = "textBoxFileSpec";
            this.textBoxFileSpec.Size = new System.Drawing.Size(390, 20);
            this.textBoxFileSpec.TabIndex = 1;
            this.textBoxFileSpec.TextChanged += new System.EventHandler(this.textBoxFileSpec_TextChanged);
            // 
            // buttonBrowse
            // 
            this.buttonBrowse.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.buttonBrowse.AutoSize = true;
            this.buttonBrowse.Location = new System.Drawing.Point(494, 13);
            this.buttonBrowse.Margin = new System.Windows.Forms.Padding(0);
            this.buttonBrowse.Name = "buttonBrowse";
            this.buttonBrowse.Size = new System.Drawing.Size(75, 23);
            this.buttonBrowse.TabIndex = 2;
            this.buttonBrowse.Text = "Browse...";
            this.buttonBrowse.Click += new System.EventHandler(this.buttonBrowse_Click);
            // 
            // labelPython3Path
            // 
            this.labelPython3Path.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.labelPython3Path.AutoSize = true;
            this.labelPython3Path.Location = new System.Drawing.Point(5, 50);
            this.labelPython3Path.Name = "labelPython3Path";
            this.labelPython3Path.Padding = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.labelPython3Path.Size = new System.Drawing.Size(96, 18);
            this.labelPython3Path.TabIndex = 5;
            this.labelPython3Path.Text = "Python3 DLL path:";
            // 
            // textBoxPython3Path
            // 
            this.textBoxPython3Path.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBoxPython3Path.Location = new System.Drawing.Point(107, 53);
            this.textBoxPython3Path.Name = "textBoxPython3Path";
            this.textBoxPython3Path.Size = new System.Drawing.Size(384, 20);
            this.textBoxPython3Path.TabIndex = 6;
            // 
            // buttonPython3Browse
            // 
            this.buttonPython3Browse.AutoSize = true;
            this.buttonPython3Browse.Location = new System.Drawing.Point(494, 50);
            this.buttonPython3Browse.Margin = new System.Windows.Forms.Padding(0);
            this.buttonPython3Browse.Name = "buttonPython3Browse";
            this.buttonPython3Browse.Padding = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.buttonPython3Browse.Size = new System.Drawing.Size(75, 25);
            this.buttonPython3Browse.TabIndex = 2;
            this.buttonPython3Browse.Text = "Browse...";
            this.buttonPython3Browse.Click += new System.EventHandler(this.buttonBrowseForPythonDll_Click);
            // 
            // openFileDialogBrowse
            // 
            this.openFileDialogBrowse.DefaultExt = "py";
            this.openFileDialogBrowse.Filter = "Python scrips (*.py)|*.py";
            this.openFileDialogBrowse.Title = "Browse for Python script";
            // 
            // Py3ScriptAutoConfigDialog
            // 
            this.ClientSize = new System.Drawing.Size(634, 479);
            this.Name = "Py3ScriptAutoConfigDialog";
            this.Controls.SetChildIndex(this.tabControl, 0);
            this.Controls.SetChildIndex(this.buttonApply, 0);
            this.Controls.SetChildIndex(this.buttonCancel, 0);
            this.Controls.SetChildIndex(this.buttonOK, 0);
            this.Controls.SetChildIndex(this.buttonSaveInRepository, 0);
            this.tabControl.ResumeLayout(false);
            this.tabPageSetup.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Label labelScriptFile;
        private System.Windows.Forms.TextBox textBoxFileSpec;
        private System.Windows.Forms.Button buttonBrowse;
        private System.Windows.Forms.OpenFileDialog openFileDialogBrowse;
        private Label labelPython3Path;
        private TextBox textBoxPython3Path;
        private Button buttonPython3Browse;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
    }
}
