using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SilEncConverters40
{
    partial class PyScriptAutoConfigDialog
    {
        #region Windows Form Designer generated code
        // This code does not get generated by Designer, so modify it directly.
        private void InitializeComponent()
        {
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.labelScriptFile = new System.Windows.Forms.Label();
            this.textBoxFileSpec = new System.Windows.Forms.TextBox();
            this.buttonBrowse = new System.Windows.Forms.Button();
            this.groupBoxExpects = new System.Windows.Forms.GroupBox();
            this.radioButtonExpectsUnicode = new System.Windows.Forms.RadioButton();
            this.radioButtonExpectsLegacy = new System.Windows.Forms.RadioButton();
            this.groupBoxReturns = new System.Windows.Forms.GroupBox();
            this.radioButtonReturnsUnicode = new System.Windows.Forms.RadioButton();
            this.radioButtonReturnsLegacy = new System.Windows.Forms.RadioButton();
            this.openFileDialogBrowse = new System.Windows.Forms.OpenFileDialog();
            this.tabControl.SuspendLayout();
            this.tabPageSetup.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.groupBoxExpects.SuspendLayout();
            this.groupBoxReturns.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabPageSetup
            // 
            this.tabPageSetup.Controls.Add(this.tableLayoutPanel1);
            // 
            // buttonApply
            // 
            this.helpProvider.SetHelpString(this.buttonApply, "Click this button to apply the configured values for this converter");
            this.helpProvider.SetShowHelp(this.buttonApply, true);
            // 
            // buttonCancel
            // 
            this.helpProvider.SetHelpString(this.buttonCancel, "Click this button to cancel this dialog");
            this.helpProvider.SetShowHelp(this.buttonCancel, true);
            // 
            // buttonOK
            // 
            this.helpProvider.SetHelpString(this.buttonOK, "Click this button to accept the configured values for this converter");
            this.helpProvider.SetShowHelp(this.buttonOK, true);
            // 
            // buttonSaveInRepository
            // 
            this.helpProvider.SetHelpString(this.buttonSaveInRepository, "Click to add this converter to the system repository permanently.");
            this.helpProvider.SetShowHelp(this.buttonSaveInRepository, true);
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 3;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 104F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel1.Controls.Add(this.labelScriptFile, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.textBoxFileSpec, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.buttonBrowse, 2, 0);
            this.tableLayoutPanel1.Controls.Add(this.groupBoxExpects, 1, 2);
            this.tableLayoutPanel1.Controls.Add(this.groupBoxReturns, 1, 3);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 5;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(596, 394);
            this.tableLayoutPanel1.TabIndex = 1;
            // 
            // labelScriptFile
            // 
            this.labelScriptFile.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.labelScriptFile.AutoSize = true;
            this.labelScriptFile.Location = new System.Drawing.Point(14, 18);
            this.labelScriptFile.Name = "labelScriptFile";
            this.labelScriptFile.Size = new System.Drawing.Size(87, 13);
            this.labelScriptFile.TabIndex = 0;
            this.labelScriptFile.Text = "Python script file:";
            // 
            // textBoxFileSpec
            // 
            this.textBoxFileSpec.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.textBoxFileSpec.Location = new System.Drawing.Point(104, 15);
            this.textBoxFileSpec.Margin = new System.Windows.Forms.Padding(0);
            this.textBoxFileSpec.Name = "textBoxFileSpec";
            this.textBoxFileSpec.Size = new System.Drawing.Size(390, 20);
            this.textBoxFileSpec.TabIndex = 1;
            this.textBoxFileSpec.TextChanged += new System.EventHandler(this.textBoxFileSpec_TextChanged);
            // 
            // buttonBrowse
            // 
            this.buttonBrowse.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.buttonBrowse.AutoSize = true;
            this.buttonBrowse.Location = new System.Drawing.Point(494, 13);
            this.buttonBrowse.Margin = new System.Windows.Forms.Padding(0);
            this.buttonBrowse.Name = "buttonBrowse";
            this.buttonBrowse.Size = new System.Drawing.Size(75, 23);
            this.buttonBrowse.TabIndex = 2;
            this.buttonBrowse.Text = "Browse...";
            this.buttonBrowse.Click += new System.EventHandler(this.buttonBrowse_Click);
            // 
            // groupBoxExpects
            // 
            this.groupBoxExpects.Controls.Add(this.radioButtonExpectsUnicode);
            this.groupBoxExpects.Controls.Add(this.radioButtonExpectsLegacy);
            this.groupBoxExpects.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBoxExpects.Location = new System.Drawing.Point(107, 53);
            this.groupBoxExpects.Name = "groupBoxExpects";
            this.groupBoxExpects.Size = new System.Drawing.Size(384, 77);
            this.groupBoxExpects.TabIndex = 3;
            this.groupBoxExpects.TabStop = false;
            this.groupBoxExpects.Text = "Python function expects";
            // 
            // radioButtonExpectsUnicode
            // 
            this.radioButtonExpectsUnicode.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.radioButtonExpectsUnicode.AutoSize = true;
            this.radioButtonExpectsUnicode.Location = new System.Drawing.Point(50, 30);
            this.radioButtonExpectsUnicode.Name = "radioButtonExpectsUnicode";
            this.radioButtonExpectsUnicode.Size = new System.Drawing.Size(95, 17);
            this.radioButtonExpectsUnicode.TabIndex = 0;
            this.radioButtonExpectsUnicode.TabStop = true;
            this.radioButtonExpectsUnicode.Text = "Unicode String";
            this.radioButtonExpectsUnicode.UseVisualStyleBackColor = true;
            this.radioButtonExpectsUnicode.CheckedChanged += new System.EventHandler(this.radioButton_CheckedChanged);
            // 
            // radioButtonExpectsLegacy
            // 
            this.radioButtonExpectsLegacy.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.radioButtonExpectsLegacy.AutoSize = true;
            this.radioButtonExpectsLegacy.Location = new System.Drawing.Point(200, 30);
            this.radioButtonExpectsLegacy.Name = "radioButtonExpectsLegacy";
            this.radioButtonExpectsLegacy.Size = new System.Drawing.Size(117, 17);
            this.radioButtonExpectsLegacy.TabIndex = 0;
            this.radioButtonExpectsLegacy.TabStop = true;
            this.radioButtonExpectsLegacy.Text = "Non-Unicode Bytes";
            this.radioButtonExpectsLegacy.UseVisualStyleBackColor = true;
            this.radioButtonExpectsLegacy.CheckedChanged += new System.EventHandler(this.radioButton_CheckedChanged);
            // 
            // groupBoxReturns
            // 
            this.groupBoxReturns.Controls.Add(this.radioButtonReturnsUnicode);
            this.groupBoxReturns.Controls.Add(this.radioButtonReturnsLegacy);
            this.groupBoxReturns.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBoxReturns.Location = new System.Drawing.Point(107, 136);
            this.groupBoxReturns.Name = "groupBoxReturns";
            this.groupBoxReturns.Size = new System.Drawing.Size(384, 77);
            this.groupBoxReturns.TabIndex = 4;
            this.groupBoxReturns.TabStop = false;
            this.groupBoxReturns.Text = "Python function returns";
            // 
            // radioButtonReturnsUnicode
            // 
            this.radioButtonReturnsUnicode.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.radioButtonReturnsUnicode.AutoSize = true;
            this.radioButtonReturnsUnicode.Location = new System.Drawing.Point(50, 30);
            this.radioButtonReturnsUnicode.Name = "radioButtonReturnsUnicode";
            this.radioButtonReturnsUnicode.Size = new System.Drawing.Size(95, 17);
            this.radioButtonReturnsUnicode.TabIndex = 0;
            this.radioButtonReturnsUnicode.TabStop = true;
            this.radioButtonReturnsUnicode.Text = "Unicode String";
            this.radioButtonReturnsUnicode.UseVisualStyleBackColor = true;
            this.radioButtonReturnsUnicode.CheckedChanged += new System.EventHandler(this.radioButton_CheckedChanged);
            // 
            // radioButtonReturnsLegacy
            // 
            this.radioButtonReturnsLegacy.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.radioButtonReturnsLegacy.AutoSize = true;
            this.radioButtonReturnsLegacy.Location = new System.Drawing.Point(200, 30);
            this.radioButtonReturnsLegacy.Name = "radioButtonReturnsLegacy";
            this.radioButtonReturnsLegacy.Size = new System.Drawing.Size(118, 17);
            this.radioButtonReturnsLegacy.TabIndex = 0;
            this.radioButtonReturnsLegacy.TabStop = true;
            this.radioButtonReturnsLegacy.Text = "Non-Unicode String";
            this.radioButtonReturnsLegacy.UseVisualStyleBackColor = true;
            this.radioButtonReturnsLegacy.CheckedChanged += new System.EventHandler(this.radioButton_CheckedChanged);
            // 
            // openFileDialogBrowse
            // 
            this.openFileDialogBrowse.DefaultExt = "py";
            this.openFileDialogBrowse.Filter = "Python scrips (*.py)|*.py";
            this.openFileDialogBrowse.Title = "Browse for Python script";
            // 
            // PyScriptAutoConfigDialog
            // 
            this.ClientSize = new System.Drawing.Size(634, 479);
            this.Name = "PyScriptAutoConfigDialog";
            this.Controls.SetChildIndex(this.tabControl, 0);
            this.Controls.SetChildIndex(this.buttonApply, 0);
            this.Controls.SetChildIndex(this.buttonCancel, 0);
            this.Controls.SetChildIndex(this.buttonOK, 0);
            this.Controls.SetChildIndex(this.buttonSaveInRepository, 0);
            this.tabControl.ResumeLayout(false);
            this.tabPageSetup.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            this.groupBoxExpects.ResumeLayout(false);
            this.groupBoxExpects.PerformLayout();
            this.groupBoxReturns.ResumeLayout(false);
            this.groupBoxReturns.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Label labelScriptFile;
        private System.Windows.Forms.TextBox textBoxFileSpec;
        private System.Windows.Forms.Button buttonBrowse;
        private System.Windows.Forms.OpenFileDialog openFileDialogBrowse;
        private System.Windows.Forms.GroupBox groupBoxExpects;
        private System.Windows.Forms.RadioButton radioButtonExpectsUnicode;
        private System.Windows.Forms.RadioButton radioButtonExpectsLegacy;
        private System.Windows.Forms.GroupBox groupBoxReturns;
        private System.Windows.Forms.RadioButton radioButtonReturnsLegacy;
        private System.Windows.Forms.RadioButton radioButtonReturnsUnicode;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
    }
}
