//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilEncConverters40.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SourceFont\r\nHeight\t-19\r\nWidth\t0\r\nEscapement\t0\r\nOrientation\t0\r\nWeight\t700\r\nItalic\t" +
            "0\r\nUnderline\t0\r\nStrikeOut\t0\r\nFontEncoding\t33\r\nCharSet\t0\r\nOutPrecision\t3\r\nClipPre" +
            "cision\t2\r\nQuality\t1\r\nPitchAndFamily\t34\r\nFaceName\t{0}\r\nColor\t16711680\r\n\r\nTargetFo" +
            "nt\r\nHeight\t-19\r\nWidth\t0\r\nEscapement\t0\r\nOrientation\t0\r\nWeight\t700\r\nItalic\t0\r\nUnde" +
            "rline\t0\r\nStrikeOut\t0\r\nFontEncoding\t33\r\nCharSet\t0\r\nOutPrecision\t3\r\nClipPrecision\t" +
            "2\r\nQuality\t1\r\nPitchAndFamily\t34\r\nFaceName\t{1}\r\nColor\t0\r\n\r\nNavTextFont\r\nHeight\t-1" +
            "5\r\nWidth\t7\r\nEscapement\t0\r\nOrientation\t0\r\nWeight\t700\r\nItalic\t0\r\nUnderline\t0\r\nStri" +
            "keOut\t0\r\nFontEncoding\t33\r\nCharSet\t0\r\nOutPrecision\t1\r\nClipPrecision\t2\r\nQuality\t2\r" +
            "\nPitchAndFamily\t34\r\nFaceName\t{2}\r\nColor\t65280\r\n\r\nProjectSettings\r\nSourceLanguage" +
            "Name\t{3}\r\nTargetLanguageName\t{4}\r\nDefaultCCTablePath\t\r\nLastExportPath\t\r\nLastNewD" +
            "ocumentFolder\t{5}\\Adapt It Unicode Work\r\nPunctuationPairsSourceSet(stores space " +
            "for an empty cell)\t{6}\r\nPunctuationPairsTargetSet(stores space for an empty cell" +
            ")\t{7}\r\n\r\nPunctuationTwoCharacterPairsSourceSet(ditto)\t\r\nPunctuationTwoCharacterP" +
            "airsTargetSet(ditto)\t\r\nSpecialTextColor\t255\r\nRetranslationTextColor\t32896\r\nColor" +
            "OfNavigationText\t65280\r\nBackupDocumentFlag\t0\r\nRTL_Layout\t0\r\nSFMescapeChar\t\\\r\nSFM" +
            "afterNewlines\t0\r\nSourceIsRTL\t{8}\r\nTargetIsRTL\t{9}\r\n\r\nNavTextIsRTL\t0\r\nLowerCaseSo" +
            "urceLanguageChars\tabcdefghijklmnopqrstuvwxyz\r\nUpperCaseSourceLanguageChars\tABCDE" +
            "FGHIJKLMNOPQRSTUVWXYZ\r\nLowerCaseTargetLanguageChars\tabcdefghijklmnopqrstuvwxyz\r\n" +
            "UpperCaseTargetLanguageChars\tABCDEFGHIJKLMNOPQRSTUVWXYZ\r\nLowerCaseGlossLanguageC" +
            "hars\tabcdefghijklmnopqrstuvwxyz\r\nUpperCaseGlossLanguageChars\tABCDEFGHIJKLMNOPQRS" +
            "TUVWXYZ\r\nAutoCapitalizationFlag\t0\r\nSourceHasUpperCaseAndLowerCase\t0\r\nFontSizeFor" +
            "Dialogs(points)\t12\r\nUseSFMarkerSet\tUsfmOnly\r\nUseFilterMarkers\t\\_list_base \\xdc \\" +
            "lit \\_double_boxed_para \\_body_text \\bt \\ef \\x \\_normal_table \\_footnote_caller " +
            "\\_dft_para_font \\h \\_unknown_para_style \\_annotation_ref \\note \\rem \\_annotation" +
            "_text \\_peripherals_base \\_heading_base \\_hdr_ftr_interlinear \\__normal \\xk \\ide" +
            " \\_horiz_rule \\_vernacular_base \\_small_para_break \\mr \\_notes_base \\_nav_lang_i" +
            "nterlinear \\efm \\pro \\restore \\_footer \\xo \\_single_boxed_para \\_src_lang_interl" +
            "inear \\cl \\_unknown_char_style \\ib \\xq \\_header \\vp \\_hidden_note \\_tgt_lang_int" +
            "erlinear \\free \\r \\_gls_lang_interlinear \\ie \\xt \\va \\cp \\h1 \\h2 \\_table_grid \\_" +
            "intro_base \\fig \\ca \\h3 \\rq \r\nChangeFixedSpaceToRegularSpace\t0\r\nBookModeFlag\t0\r\n" +
            "BookIndexValue\t-1\r\nSaveAsXML\t1\r\nSilConverterName\t\r\nSilConverterDirectionForward\t" +
            "1\r\nSilConverterNormalizeOutput\t0\r\nLegacyCopyForPhraseBox\t1\r\nDoAdaptingBeforeGlos" +
            "sing_InVerticalEdit\t1")]
        public string DefaultAIProjectFile {
            get {
                return ((string)(this["DefaultAIProjectFile"]));
            }
            set {
                this["DefaultAIProjectFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<!--
	 Note: Using Microsoft WORD 2003 or later is not a good way to edit this xml file.
	 Instead, use NotePad, WordPad or Windows Explorer.
	 Please note: the order of the TU elements in this xml file might differ each time the knowledge base is saved. This is not an error. -->
<KB docVersion=""4"" srcName=""{0}"" tgtName=""{1}"" max=""1"">
	<MAP mn=""1"">
	</MAP>
</KB>
")]
        public string DefaultAIKBFile {
            get {
                return ((string)(this["DefaultAIKBFile"]));
            }
            set {
                this["DefaultAIKBFile"] = value;
            }
        }
    }
}
