//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilEncConverters40.EcTranslators.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilEncConverters40.EcTranslators.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this button to enter your own API key from Microsoft Azure. See the &quot;Prerequisites&quot; section on the page, https://docs.microsoft.com/en-us/azure/cognitive-services/translator/quickstart-translator, for how to get your own key (e.g. if the default API key has run out of translation support -- note: the default API key is using the free pricing tier and is limited to 2 million characters/month).
        /// </summary>
        internal static string HelpForBingTranslatorAddYourOwnApiKey {
            get {
                return ResourceManager.GetString("HelpForBingTranslatorAddYourOwnApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this option to create a dictionary lookup converter for a word from one language to another. If there are multiple translations for a given word, then the converted text will be in the Ample ambiguity form (i.e. &quot;%&lt;count=n&gt;%&lt;translation_1&gt;%&lt;translation_2&gt;%...%&lt;translation_n&gt;%&quot;, e.g. &quot;%2%from%with%&quot;). Note: if there are multiple words in the input text, the lookup will only return data for the first word.
        ///See the Dictionary column in the chart on the webpage: https://docs.microsoft.com/en-us/azure/co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpForBingTranslatorRadioButtonDictionaryLookup {
            get {
                return ResourceManager.GetString("HelpForBingTranslatorRadioButtonDictionaryLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this option to create a translator from one language to another, or from &apos;Any&apos; language (aka. Auto-Detect) to some target language
        ///See https://docs.microsoft.com/en-us/azure/cognitive-services/translator/language-support to see which languages are supported..
        /// </summary>
        internal static string HelpForBingTranslatorRadioButtonTranslate {
            get {
                return ResourceManager.GetString("HelpForBingTranslatorRadioButtonTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this option to create a translator from one language to another, or from &apos;Any&apos; language (aka. Auto-Detect) to some target language AND transliterate the result into another script (currently, only Latin supported).
        ///See https://docs.microsoft.com/en-us/azure/cognitive-services/translator/language-support to see which languages and transliterated scripts are supported..
        /// </summary>
        internal static string HelpForBingTranslatorRadioButtonTranslateWithTransliteration {
            get {
                return ResourceManager.GetString("HelpForBingTranslatorRadioButtonTranslateWithTransliteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this option to create a transliterator from one script to another for a given Source language.
        ///See https://docs.microsoft.com/en-us/azure/cognitive-services/translator/language-support to see which languages and transliterated scripts are supported..
        /// </summary>
        internal static string HelpForBingTranslatorRadioButtonTransliterate {
            get {
                return ResourceManager.GetString("HelpForBingTranslatorRadioButtonTransliterate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the language you want to translate or transliterate from. Choose &apos;Auto-Detect&apos; if you want the underlying Bing Translator to attempt to determine the input language. See https://docs.microsoft.com/en-us/azure/cognitive-services/translator/language-support to see which languages support Auto language detection..
        /// </summary>
        internal static string HelpForBingTranslatorSourceLanguagesComboBox {
            get {
                return ResourceManager.GetString("HelpForBingTranslatorSourceLanguagesComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This box shows the expected script of the input text before it is transliterated..
        /// </summary>
        internal static string HelpForBingTranslatorSourceScriptTextBox {
            get {
                return ResourceManager.GetString("HelpForBingTranslatorSourceScriptTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the language you want the input text to be translated into..
        /// </summary>
        internal static string HelpForBingTranslatorTargetLanguagesComboBox {
            get {
                return ResourceManager.GetString("HelpForBingTranslatorTargetLanguagesComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the script you want the input text (or the translated text, in the &apos;Translate + Transliterate&apos; case) to be transliterated into..
        /// </summary>
        internal static string HelpForBingTranslatorTargetScriptsComboBox {
            get {
                return ResourceManager.GetString("HelpForBingTranslatorTargetScriptsComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this button to enter your own API key from DeepL. See the &quot;Find your perfect plan&quot; section on the page, https://www.deepl.com/pro?cta=header-pro, for how to get your own key (e.g. if the default API key has run out of translation support -- note: the default API key is using the free pricing tier and is limited to 500K characters/month for all users).
        /// </summary>
        internal static string HelpForDeepLTranslatorAddYourOwnApiKey {
            get {
                return ResourceManager.GetString("HelpForDeepLTranslatorAddYourOwnApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the language you want to translate into (i.e. Target language) supports formality, then these radio buttons will be enabled allowing you to choose between more or less formality during translation..
        /// </summary>
        internal static string HelpForDeepLTranslatorFormalityLevel {
            get {
                return ResourceManager.GetString("HelpForDeepLTranslatorFormalityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the language you want to translate or transliterate from. Choose &apos;Auto-Detect&apos; if you want the underlying DeepL Translator to attempt to determine the input language..
        /// </summary>
        internal static string HelpForDeepLTranslatorSourceLanguagesComboBox {
            get {
                return ResourceManager.GetString("HelpForDeepLTranslatorSourceLanguagesComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the language you want the input text to be translated into..
        /// </summary>
        internal static string HelpForDeepLTranslatorTargetLanguagesComboBox {
            get {
                return ResourceManager.GetString("HelpForDeepLTranslatorTargetLanguagesComboBox", resourceCulture);
            }
        }
    }
}
