//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilEncConverters40.EcTranslators.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QMuB0FScN6S0HBybzZkTbPjOTzxAwCwp0Lz3sKUVPDOa0nrUhgUcgQ==")]
        public string AzureTranslatorKey {
            get {
                return ((string)(this["AzureTranslatorKey"]));
            }
            set {
                this["AzureTranslatorKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("global")]
        public string AzureTranslatorRegion {
            get {
                return ((string)(this["AzureTranslatorRegion"]));
            }
            set {
                this["AzureTranslatorRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.cognitive.microsofttranslator.com/")]
        public string AzureTranslatorTextTranslationEndpoint {
            get {
                return ((string)(this["AzureTranslatorTextTranslationEndpoint"]));
            }
            set {
                this["AzureTranslatorTextTranslationEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://docs.microsoft.com/en-us/azure/cognitive-services/translator/quickstart-t" +
            "ranslator")]
        public string AzureTranslatorKeyLocationDialogInstructionUrl {
            get {
                return ((string)(this["AzureTranslatorKeyLocationDialogInstructionUrl"]));
            }
            set {
                this["AzureTranslatorKeyLocationDialogInstructionUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AzureTranslatorKeyOverride {
            get {
                return ((string)(this["AzureTranslatorKeyOverride"]));
            }
            set {
                this["AzureTranslatorKeyOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X1jOy3rXKfQl20lvyoj7LYlLtEuaRITqjY+oGo4BYCpE6/4MQ9kQFA==")]
        public string DeepLTranslatorKey {
            get {
                return ((string)(this["DeepLTranslatorKey"]));
            }
            set {
                this["DeepLTranslatorKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeepLTranslatorKeyOverride {
            get {
                return ((string)(this["DeepLTranslatorKeyOverride"]));
            }
            set {
                this["DeepLTranslatorKeyOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.deepl.com/pro?cta=header-pro/")]
        public string DeepLTranslatorKeyDialogInstructionUrl {
            get {
                return ((string)(this["DeepLTranslatorKeyDialogInstructionUrl"]));
            }
            set {
                this["DeepLTranslatorKeyDialogInstructionUrl"] = value;
            }
        }
    }
}
