.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ENC-CONVERTERS 3 "January 23, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
enc-converters \- libraries to convert text from one encoding to another
.SH SYNOPSIS
.B enc-converters
.SH DESCRIPTION
This manual page documents briefly the
.B enc-converters
package of libraries.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBenc-converters\fP is a set of libraries written in either C# or C++ to
convert text from one encoding to another.  A variety of engines are
supported, ranging from the SIL-written consistent changes processor to ICU
transliterators to Python scripts to ....
.SH SEE ALSO
I'm sure there's documentation on all this stuff somewhere.
.SH AUTHOR
enc-converters was written by Bob Eaton.
.PP
This manual page was written by Stephen McConnel <stephen_mcconnel@sil.org>,
as a stopgap measure (and may be used by others).
