//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilEncConverters40.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>{[aeiou]}-&gt;{V};1</string>
  <string>{[^aeiou]}-&gt;{C};1</string>
  <string>{[\u0027\u002a\u2018\u2019\u201c\u201d\u0303\u0304\u0310\u0314\u0325\u200c\u200d\uE03C\uFFFD]}-&gt;{};</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RecentRegExpressions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentRegExpressions"]));
            }
            set {
                this["RecentRegExpressions"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\r|\\\\n|\\\\t|\\\\u[0-9a-fA-F]{4}")]
        public string RegexNetLettersToUnescape {
            get {
                return ((string)(this["RegexNetLettersToUnescape"]));
            }
        }

        // Application-scoped (read-only at runtime, editable only via the installed *.config file --
        // see EncConverter.RiskyNativeDependencies and Handover.md, "Generic subprocess fallback for
        // host-process conflicts"): lets a newly-discovered risky native DLL (one not caught during
        // testing, so no EncConverter subclass declares it in code) be added after deployment without
        // rebuilding -- add a <string> entry to this setting's <value> in the installed .config file.
        // Merged with (not a replacement for) whatever each EncConverter subclass declares in code; see
        // TechHindiSiteEncConverter.RiskyNativeDependencies for the merge pattern.
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" />")]
        public global::System.Collections.Specialized.StringCollection AdditionalRiskyNativeDependencies {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AdditionalRiskyNativeDependencies"]));
            }
        }
    }
}
